version: '3.8'

services:
  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: "ajdlfjsdfhoweoriuweralsjfowerhlhaskdfjlkeiurpoweuriou;asjfjfjlkaflkja;fkvznx,n"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "@pankaj123"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@pankaj123"
      MYSQL_DATABASE: cms
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: