
#mysql config
spring.datasource.url=${SPRING.DATASOURCE.URL}
spring.datasource.username=${SPRING.DATASOURCE.USERNAME}
spring.datasource.password=${SPRING.DATASOURCE.PASSWORD}

#jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



